---
include:
  # ───────────────────────────────────────────────────────────────
  # normal right half
  # ───────────────────────────────────────────────────────────────
  - board: eyelash_corne_right
    shield: nice_view                     # no extra cmake-args needed
    cmake-args: >-
      -DZMK_EXTRA_MODULES="$base_dir/modules/zmk-helpers"

  # ───────────────────────────────────────────────────────────────
  # normal left half — with ZMK-Studio telemetry
  # ───────────────────────────────────────────────────────────────
  - board: eyelash_corne_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: >-
      -DCONFIG_ZMK_STUDIO=y
      -DCONFIG_ZMK_STUDIO_LOCKING=n       # module path comes from workflow
      -DZMK_EXTRA_MODULES="$base_dir/modules/zmk-helpers"
    artifact-name: eyelash_corne_studio_left

  # ───────────────────────────────────────────────────────────────
  # “settings-reset” image (clears persistent settings)
  # ───────────────────────────────────────────────────────────────
  - board: eyelash_corne_left
    shield: settings_reset                # no extra cmake-args needed
    cmake-args: >-
      -DZMK_EXTRA_MODULES="$base_dir/modules/zmk-helpers"
