name: Build ZMK firmware

on:
  # run on demand …
  workflow_dispatch:
  # … or whenever anything except the keymap-drawer artefacts changes
  push:
    paths-ignore:
      - "keymap-drawer/**"

jobs:
  build:
    # Re-use ZMK’s official workflow
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

    # ───────────── optional but explicit ─────────────
    # the defaults are already “build.yaml” and “config”,
    # but it’s clearer (and future-proof) to wire them up:
    with:
      build_matrix_path: build.yaml   # matrix that lists all boards to build
      config_path:       config       # your ZMK config folder
      archive_name:      firmware     # final artefact name (zip)
